window.BANK_eigoB = [
  { id:"eig-051", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"I ( ) here since 2020.", o:["have lived","live","lived","am living"], a:0, e:"sinceは「〜以来」を表し、過去から現在まで続く状態は現在完了で表す。", lv:1 },
  { id:"eig-052", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"By the time she arrived, the meeting already ( ).", o:["started","had started","has started","starts"], a:1, e:"過去のある時点までに完了していたことは過去完了(had+過去分詞)で表す。", t:"alreadyは肯定文、yetは疑問文・否定文でよく使われる。", lv:2 },
  { id:"eig-053", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"Look at those clouds! It ( ) rain soon.", o:["will","would","is going to","has"], a:2, e:"目に見える証拠に基づく予測にはbe going toを使う。", lv:2 },
  { id:"eig-054", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"I ( ) my dentist tomorrow afternoon.", o:["see","saw","have seen","am seeing"], a:3, e:"確定した予定はam/is/are+doing(現在進行形)で表せる。", t:"willは瞬間的な決定、be going toは既定の予定に使うと覚える。", lv:2 },
  { id:"eig-055", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語を選べ。", s:"We have known each other ( ) ten years.", o:["for","since","during","while"], a:0, e:"forは期間の長さ、sinceは起点を表す。ten yearsは期間なのでforが正しい。", lv:1 },
  { id:"eig-056", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"I ( ) dinner when the phone rang.", o:["cook","was cooking","cooked","have cooked"], a:1, e:"過去のある動作の最中に別の出来事が起きたときは過去進行形を使う。", lv:2 },
  { id:"eig-057", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"By next April, he ( ) here for five years.", o:["worked","will work","will have worked","has worked"], a:2, e:"未来のある時点までの完了・継続はwill have+過去分詞(未来完了)で表す。", t:"未来完了はwill haveと「未来のある時点」を表す語句をセットで覚える。", lv:3 },
  { id:"eig-058", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語を選べ。", s:"I have ( ) finished my homework.", o:["yesterday","ago","last night","just"], a:3, e:"just, already, yetなどは現在完了とともによく使う副詞。過去の一点を示す語とは併用しない。", lv:1 },

  { id:"eig-059", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"The man ( ) car was stolen called the police.", o:["whose","who","whom","which"], a:0, e:"後ろに名詞(car)が続き所有を表すのでwhoseを使う。", lv:3 },
  { id:"eig-060", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"She is the woman ( ) helped me yesterday.", o:["which","who","whose","whom"], a:1, e:"先行詞が人で、関係詞節の中で主語の働きをするのでwhoを使う。", t:"先行詞が人か物かでwho/whichを使い分ける。", lv:2 },
  { id:"eig-061", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"He passed the exam, ( ) surprised everyone.", o:["that","what","which","who"], a:2, e:"前の文全体を先行詞とする非制限用法の関係代名詞はwhichを使う。", lv:3 },
  { id:"eig-062", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"This is the town ( ) I was born.", o:["which","who","whose","where"], a:3, e:"先行詞が場所で、関係詞節が完全な文になっているのでwhereを使う。", lv:2 },
  { id:"eig-063", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"( ) he said was true.", o:["What","That","Which","Who"], a:0, e:"先行詞を含む関係代名詞whatは「〜すること・もの」を表し、文頭で主語になれる。", lv:2 },
  { id:"eig-064", cat:"英語", sub:"文法・関係詞", q:"次の文の空所に入れられないものはどれか。", s:"This is the book ( ) I bought yesterday.", o:["which","whom","that","(省略可)"], a:1, e:"先行詞the bookは物なのでwhomは使えない。目的格の関係代名詞は省略も可能。", t:"目的格の関係代名詞は省略できることも覚えておこう。", lv:2 },

  { id:"eig-065", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語を選べ。", s:"If I ( ) you, I would apologize.", o:["am","was","were","be"], a:2, e:"仮定法過去では主語に関わらずbe動詞はwereを使うのが原則。", lv:1 },
  { id:"eig-066", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語句を選べ。", s:"If she had studied harder, she ( ) the exam.", o:["would pass","passes","had passed","would have passed"], a:3, e:"仮定法過去完了はif+had+過去分詞, 主語+would have+過去分詞の形をとる。", lv:3 },
  { id:"eig-067", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語を選べ。", s:"I wish I ( ) more free time.", o:["had","have","will have","having"], a:0, e:"現在の事実に反する願望はwish+主語+過去形で表す。", t:"wish+過去形は現在の願望、wish+had+過去分詞は過去の願望を表す。", lv:1 },
  { id:"eig-068", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語句を選べ。", s:"I wish I ( ) the truth earlier.", o:["knew","had known","know","have known"], a:1, e:"過去の事実に反する願望はwish+主語+had+過去分詞で表す。", lv:3 },
  { id:"eig-069", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語を選べ。", s:"He talks as if he ( ) everything.", o:["knows","known","knew","has known"], a:2, e:"as ifの後で現実と異なる内容を述べるときは過去形(仮定法過去)を使う。", t:"as ifの後は現実との違いを表すため、時制を一つ過去にずらすのが基本。", lv:2 },

  { id:"eig-070", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語句を選べ。", s:"This bag is ( ) as that one.", o:["heavy","heavier","the heaviest","as heavy"], a:3, e:"原級比較はas+形容詞の原級+asの形で表す。", lv:2 },
  { id:"eig-071", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語句を選べ。", s:"The more you practice, ( ) you become.", o:["the better","better","the best","good"], a:0, e:"「〜すればするほど…」はthe+比較級, the+比較級の構文で表す。", lv:2 },
  { id:"eig-072", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語句を選べ。", s:"Mt. Fuji is ( ) mountain in Japan.", o:["higher","the highest","highest","the higher"], a:1, e:"最上級には通常theを付ける。the+最上級で「最も〜」を表す。", lv:2 },
  { id:"eig-073", cat:"英語", sub:"文法・比較", q:"次の文とほぼ同じ意味になるものを選べ。", s:"Tom is not as tall as Ken.", o:["Tom is taller than Ken.","Tom and Ken are the same height.","Ken is taller than Tom.","Ken is not tall."], a:2, e:"「TomはKenほど背が高くない」は「Kenの方が背が高い」と同義。", t:"notを含む比較の文は、逆の立場から言い換えると意味を取りやすい。", lv:2 },
  { id:"eig-074", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語を選べ。", s:"This question is ( ) difficult than the last one.", o:["fewer","least","the less","less"], a:3, e:"数えられない性質・程度の少なさはlessで表す。fewerは数えられる名詞に使う。", lv:3 },

  { id:"eig-075", cat:"英語", sub:"不規則動詞", q:"goの過去分詞形として正しいものはどれか。", o:["gone","went","goed","going"], a:0, e:"go-went-goneと変化する。過去分詞はgone。", lv:1 },
  { id:"eig-076", cat:"英語", sub:"不規則動詞", q:"breakの過去形として正しいものはどれか。", o:["breaked","broke","broken","break"], a:1, e:"break-broke-brokenと変化する。過去形はbroke。", t:"不規則動詞の変化は語呂合わせで覚えると忘れにくい。", lv:1 },
  { id:"eig-077", cat:"英語", sub:"不規則動詞", q:"空所に入る最も適切な語を選べ。", s:"I have already ( ) the letter.", o:["wrote","writing","written","writes"], a:2, e:"write-wrote-writtenと変化する。現在完了には過去分詞writtenを使う。", lv:2 },
  { id:"eig-078", cat:"英語", sub:"不規則動詞", q:"空所に入る最も適切な語を選べ。", s:"The concert ( ) at seven last night.", o:["begun","begins","beginned","began"], a:3, e:"begin-began-begunと変化する。過去形はbegan。", lv:1 },
  { id:"eig-079", cat:"英語", sub:"不規則動詞", q:"動詞の変化(原形-過去形-過去分詞)が誤っているものはどれか。", o:["catch-catched-caught","eat-ate-eaten","choose-chose-chosen","bring-brought-brought"], a:0, e:"catchの正しい変化はcatch-caught-caughtで、catchedという形は存在しない。", t:"catch-caught, teach-taughtのように-ght型の変化をまとめて覚えると良い。", lv:2 },

  { id:"eig-080", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: Could you pass me the salt? / B: ( )", o:["Nice to meet you.","Sure, here you are.","See you later.","I'm fine, thanks."], a:1, e:"依頼に応じるときはSure, here you are.のような表現が自然。", lv:1 },
  { id:"eig-081", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: How about going for a walk? / B: ( )", o:["You're welcome.","Excuse me.","That sounds great.","I'm sorry to hear that."], a:2, e:"提案に賛成するときはThat sounds great.などの表現を使う。", lv:1 },
  { id:"eig-082", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: Excuse me, may I sit here? / B: ( )", o:["It's very kind of you.","Yes, please.","Not at all, thanks.","Sure, go ahead."], a:3, e:"許可を求める May I ~? には Sure, go ahead.（どうぞ）で応じる。", t:"許可を求める疑問文には、承諾か断りかをはっきり示す表現を選ぶ。", lv:2 },
  { id:"eig-083", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: I'm sorry I'm late. / B: ( )", o:["That's all right.","You're welcome.","I hope so.","Congratulations."], a:0, e:"謝罪への返答としてはThat's all right.(大丈夫ですよ)が適切。", lv:1 },
  { id:"eig-084", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: Would you like some more coffee? / B: ( )", o:["Yes, I am.","No, thank you. I'm fine.","I'm sorry, I can't.","No, I don't."], a:1, e:"勧められたものを断るときはNo, thank you. I'm fine.のように答える。", lv:1 },
  { id:"eig-085", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: How long does it take to get to the station? / B: ( )", o:["I like the station.","It's on Monday.","About ten minutes by bus.","I go there every day."], a:2, e:"所要時間を尋ねる質問には具体的な時間で答える。", t:"How longの質問には具体的な時間や期間で答える。", lv:2 },

  { id:"eig-086", cat:"英語", sub:"長文読解", q:"本文の内容と一致するものはどれか。", s:"Many cities are building more bicycle lanes. This helps reduce traffic jams. It also lowers air pollution. Riding a bike is good exercise, too. In some countries, more people now bike to work than before. Local governments often give money to support these programs. Bicycle sharing systems have become popular in big cities. They let people rent bikes for short trips easily.", o:["自転車通勤をする人は年々減っている。","自転車シェアリングの人気は落ちている。","自治体は自転車政策に資金を出さない。","自転車道の整備は渋滞緩和に役立つ。"], a:3, e:"本文2文目に、自転車道の整備は交通渋滞を減らすのに役立つとある。", lv:1 },
  { id:"eig-087", cat:"英語", sub:"長文読解", q:"本文によると、水分不足で起こりやすいものはどれか。", s:"Water is essential for all living things. The human body is about sixty percent water. We lose water every day through sweat and breathing. That is why we need to drink water regularly. Doctors often suggest drinking about two liters a day. However, the right amount can change with exercise and weather. Drinking too little water can cause headaches and tiredness. Drinking enough water keeps our brain and body working well.", o:["頭痛や疲労感","視力の向上","体重の増加","筋肉の強化"], a:0, e:"本文後半に、水分が少なすぎると頭痛や疲労感を引き起こすとある。", lv:1 },
  { id:"eig-088", cat:"英語", sub:"長文読解", q:"在宅勤務について本文が述べていないことはどれか。", s:"Many companies now let employees work from home. This can save time and money on commuting. Workers often feel more relaxed at home. However, some people miss talking with coworkers in person. Managers sometimes worry about checking on progress. Many companies now use online meetings instead. Some workers say they focus better without office noise. Others find it hard to separate work from daily life.", o:["通勤時間や交通費を減らせる。","全ての社員が満足している。","同僚と話す機会が減る。","オンライン会議で連絡を取る。"], a:1, e:"本文には満足していない人もいると書かれており、全員が満足しているとは述べていない。", t:"「述べられていないこと」を選ぶ問題は消去法で確実な記述を除いていく。", lv:3 },
  { id:"eig-089", cat:"英語", sub:"長文読解", q:"本文によると、就寝前の読書がスマホより良い理由は何か。", s:"Reading books before bed can help people relax. It is often better than looking at a phone screen. Phone light can make it harder to fall asleep. Reading a paper book does not have this problem. Some studies show that reading lowers stress levels. A calm mind usually leads to better sleep. Even ten minutes of reading can make a difference. Try turning off your phone and picking up a book tonight.", o:["本が安いから","内容が面白いから","スマホの光で寝つきが悪くなるから","スマホが重すぎるから"], a:2, e:"本文に、スマホの光は寝つきを悪くするので紙の本の方が問題がないとある。", lv:2 },
  { id:"eig-090", cat:"英語", sub:"長文読解", q:"本文の内容と一致するものはどれか。", s:"Farmers around the world face new problems from climate change. Rain patterns are becoming less predictable. Some areas now get too much rain, causing floods. Other areas get too little, causing droughts. These changes make it harder to plan when to plant crops. Scientists are developing new types of seeds that can survive harsh weather. Farmers are also learning new ways to save water. Working together, they hope to keep producing enough food.", o:["全地域で雨が増えている。","科学者は種子開発をやめた。","農家は節水を学んでいない。","雨量が予測しにくくなっている。"], a:3, e:"本文2文目に、雨のパターンが予測しにくくなっているとある。", lv:2 },

  { id:"eig-091", cat:"英語", sub:"発音・アクセント", q:"下線部の発音が他と異なるものはどれか。", o:["fo【o】d","c【oo】k","b【oo】k","l【oo】k"], a:0, e:"foodの【oo】は/uː/と発音するが、他は短い/ʊ/と発音する。", t:"母音字ooやeaは単語によって発音が変わるので個別に覚える。", lv:2 },
  { id:"eig-092", cat:"英語", sub:"発音・アクセント", q:"下線部の発音が他と異なるものはどれか。", o:["br【ea】d","s【ea】","h【ea】d","w【ea】ther"], a:1, e:"seaの【ea】は/iː/と発音するが、他は/e/と発音する。", lv:2 },
  { id:"eig-093", cat:"英語", sub:"発音・アクセント", q:"最も強く発音する部分の位置が他と異なるものはどれか。", o:["【pho】to","【mu】sic","de【sign】","【pa】per"], a:2, e:"designは第2音節にアクセントがあるが、他は第1音節にアクセントがある。", lv:3 },
  { id:"eig-094", cat:"英語", sub:"発音・アクセント", q:"下線部の発音が他と異なるものはどれか。", o:["【ch】air","【ch】eese","【ch】oose","【Ch】ristmas"], a:3, e:"Christmas の ch は /k/ と発音するが、他は /tʃ/ と発音する。", t:"ギリシャ語由来の語（chemistry, character, chorus）の ch は /k/ になりやすい。", lv:3 },
  { id:"eig-095", cat:"英語", sub:"発音・アクセント", q:"最も強く発音する部分の位置が他と異なるものはどれか。", o:["ho【tel】","【ta】ble","【win】dow","【gar】den"], a:0, e:"hotelは第2音節にアクセントがあるが、他は第1音節にアクセントがある。", t:"アクセント問題は品詞で位置が変わる単語に注意する。", lv:1 }
];
