window.BANK_eigoB = [
  { id:"eig-051", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"I ( ) here since 2020.", o:["have lived","live","lived","am living"], a:0, e:"sinceは「〜以来」を表し、過去から現在まで続く状態は現在完了で表す。", k:"・現在完了（have＋過去分詞）の4用法＝継続・経験・完了・結果。継続の目印は since（〜以来）と for（〜の間）\n・since の後は起点（since 2020）、for の後は期間（for three years）\n・状態動詞 live／know は現在完了、動作動詞 wait／study は現在完了進行形で継続を表す\n・yesterday、〜ago、last week など過去の一点を示す語とは併用できない", lv:1 },
  { id:"eig-052", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"By the time she arrived, the meeting already ( ).", o:["started","had started","has started","starts"], a:1, e:"過去のある時点までに完了していたことは過去完了(had+過去分詞)で表す。", t:"alreadyは肯定文、yetは疑問文・否定文でよく使われる。", k:"・過去完了（had＋過去分詞）は過去の基準時より前に完了した出来事（大過去）。基準時は過去形の節が示す\n・目印は by the time（〜する時までに）、before、after、when＋過去形の節。文中に過去の二時点があるかを確認\n・by the time＋現在形の節なら主節は未来完了（will have＋過去分詞）。基準時が現在なら現在完了\n・had been doing（過去完了進行形）は基準時まで続いていた動作を表す", lv:2 },
  { id:"eig-053", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"Look at those clouds! It ( ) rain soon.", o:["will","would","is going to","has"], a:2, e:"目に見える証拠に基づく予測にはbe going toを使う。", k:"・be going to は目に見える兆候からの予測と、すでに決めている意図（I'm going to buy a car）を表す\n・will は話し手の推測（I think it will rain）や、その場で決めた意志（I'll answer it）\n・時刻表や公式の予定は現在形（The train leaves at 9）でも未来を表す\n・時・条件の副詞節（when／if／until）の中では未来のことも現在形", lv:2 },
  { id:"eig-054", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"I ( ) my dentist tomorrow afternoon.", o:["see","saw","have seen","am seeing"], a:3, e:"確定した予定はam/is/are+doing(現在進行形)で表せる。", t:"willは瞬間的な決定、be going toは既定の予定に使うと覚える。", k:"・現在進行形の未来用法は人と約束した手配済みの予定に使い、tomorrow／next week など未来を示す語句を伴う\n・go／come／leave／arrive／meet など往来・発着の動詞で特に多い\n・see は「見える・理解する」の意味では進行形にしないが、「会う」の意味では進行形にできる\n・進行形にしない動詞＝know／like／want／belong／have（持つ）など状態を表す動詞", lv:2 },
  { id:"eig-055", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語を選べ。", s:"We have known each other ( ) ten years.", o:["for","since","during","while"], a:0, e:"forは期間の長さ、sinceは起点を表す。ten yearsは期間なのでforが正しい。", k:"・for＋期間（for two weeks）、since＋起点（since Monday）。since の後には文も置ける\n・during（〜の間に）は名詞を伴う前置詞、while（〜する間に）は主語＋動詞を伴う接続詞\n・How long（どのくらい）の問いには for／since で答える。since を含む文の主節は現在完了が基本\n・ago（〜前に）は過去形専用", lv:1 },
  { id:"eig-056", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"I ( ) dinner when the phone rang.", o:["cook","was cooking","cooked","have cooked"], a:1, e:"過去のある動作の最中に別の出来事が起きたときは過去進行形を使う。", k:"・過去進行形（was／were＋-ing）は過去のある時点で進行中だった動作。when＋過去形の節がその時点を示す\n・while（〜している間に）の節には進行形、when の節には一瞬の動作（rang／came）が入るのが典型\n・「〜の最中に…が起きた」の型＝was doing … when … did。二つの過去形を並べると順番に起きた出来事になる", lv:2 },
  { id:"eig-057", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語句を選べ。", s:"By next April, he ( ) here for five years.", o:["worked","will work","will have worked","has worked"], a:2, e:"未来のある時点までの完了・継続はwill have+過去分詞(未来完了)で表す。", t:"未来完了はwill haveと「未来のある時点」を表す語句をセットで覚える。", k:"・未来完了（will have＋過去分詞）は未来の基準時までの完了・経験・継続。目印は by next 〜、by the time 〜\n・by（〜までに・期限）は完了形と、until／till（〜まで・継続）は stay など継続の動詞と結びつく\n・for＋期間は継続の目印。基準時が現在なら現在完了、過去なら過去完了、未来なら未来完了", lv:3 },
  { id:"eig-058", cat:"英語", sub:"文法・時制", q:"空所に入る最も適切な語を選べ。", s:"I have ( ) finished my homework.", o:["yesterday","ago","last night","just"], a:3, e:"just, already, yetなどは現在完了とともによく使う副詞。過去の一点を示す語とは併用しない。", k:"・現在完了と併用する副詞＝just（ちょうど）、already（すでに）、yet（もう／まだ）、ever（今までに）、never\n・yesterday、〜ago、last 〜、in 2010 など過去の一点を示す語は過去形と使う\n・yet は疑問文で「もう」、否定文で「まだ」。already は肯定文。just は have と過去分詞の間に置く\n・just now（たった今）は過去形と使う（I saw him just now）", lv:1 },

  { id:"eig-059", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"The man ( ) car was stolen called the police.", o:["whose","who","whom","which"], a:0, e:"後ろに名詞(car)が続き所有を表すのでwhoseを使う。", k:"・関係代名詞の格は関係詞節内の働きで決まる。主格 who／which、目的格 whom／which、所有格 whose\n・whose は先行詞が人でも物でも使え、直後に冠詞のない名詞が続く（the house whose roof is red）\n・whose＋名詞＝of which the＋名詞 に書き換え可能だが、選択肢では whose が普通\n・見分け方＝空所の直後が名詞なら whose、動詞なら主格、主語＋動詞なら目的格", lv:3 },
  { id:"eig-060", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"She is the woman ( ) helped me yesterday.", o:["which","who","whose","whom"], a:1, e:"先行詞が人で、関係詞節の中で主語の働きをするのでwhoを使う。", t:"先行詞が人か物かでwho/whichを使い分ける。", k:"・主格の関係代名詞は省略できず、直後に動詞が続く。動詞は先行詞の人称・数に一致（the people who live here）\n・that は人・物どちらにも使える。先行詞が最上級、all／every／the only を伴うときは that が好まれる\n・目的格 whom は前置詞の直後（the man to whom I spoke）で必須。会話では who で代用されやすい", lv:2 },
  { id:"eig-061", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"He passed the exam, ( ) surprised everyone.", o:["that","what","which","who"], a:2, e:"前の文全体を先行詞とする非制限用法の関係代名詞はwhichを使う。", k:"・非制限用法（コンマ＋関係詞）は先行詞に補足説明を加える。that と what は非制限用法で使えない\n・コンマ＋which は前の名詞だけでなく、前文全体・句・節の内容を受けられる。「そしてそのことは」と訳す\n・two sons, who are doctors は息子は2人だけで共に医者。コンマなしなら医者の息子が2人（他にいてもよい）\n・, who は人、, where／, when は場所・時の補足。非制限用法の関係詞は省略不可", lv:3 },
  { id:"eig-062", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"This is the town ( ) I was born.", o:["which","who","whose","where"], a:3, e:"先行詞が場所で、関係詞節が完全な文になっているのでwhereを使う。", k:"・関係副詞 where（場所）／when（時）／why（理由）／how（方法）。the way how とは言わず、どちらか一方\n・見分け方＝関係詞節が完全な文なら関係副詞、名詞が欠けていれば関係代名詞\n・where＝in／at which。which 単独なら I was born in の in が必要\n・the place／the time／the reason が先行詞なら関係副詞か先行詞の一方を省略できる", lv:2 },
  { id:"eig-063", cat:"英語", sub:"文法・関係詞", q:"空所に入る最も適切な語を選べ。", s:"( ) he said was true.", o:["What","That","Which","Who"], a:0, e:"先行詞を含む関係代名詞whatは「〜すること・もの」を表し、文頭で主語になれる。", k:"・what＝the thing(s) which。先行詞を含むので前に名詞を置かず、節全体が名詞の働き（主語・目的語・補語）\n・接続詞 that の後は完全な文。what の後は名詞が欠けた不完全な文（he said の目的語が欠落）\n・慣用表現＝what is called（いわゆる）、what he is（今の彼）\n・主語になった what 節は単数扱い（What he said was true）", lv:2 },
  { id:"eig-064", cat:"英語", sub:"文法・関係詞", q:"次の文の空所に入れられないものはどれか。", s:"This is the book ( ) I bought yesterday.", o:["which","whom","that","(省略可)"], a:1, e:"先行詞the bookは物なのでwhomは使えない。目的格の関係代名詞は省略も可能。", t:"目的格の関係代名詞は省略できることも覚えておこう。", k:"・目的格の関係代名詞（which／that／whom）は省略でき、先行詞＋主語＋動詞の形になる\n・省略できないもの＝主格の関係代名詞、前置詞の直後の関係代名詞、非制限用法の関係代名詞\n・前置詞は節末に残せる（the house which I live in）。that は前置詞の直後に置けない\n・whom は人専用、which は物専用。that は人・物両用だがコンマの後では使えない", lv:2 },

  { id:"eig-065", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語を選べ。", s:"If I ( ) you, I would apologize.", o:["am","was","were","be"], a:2, e:"仮定法過去では主語に関わらずbe動詞はwereを使うのが原則。", k:"・仮定法過去＝現在の事実に反する仮定。If＋主語＋過去形, 主語＋would／could／might＋原形\n・If I were you は助言の定型。口語では was も使われるが試験では were を選ぶ\n・直説法の if（If it rains, …）は現実にあり得る条件で現在形。違いは主節の would の有無\n・If の省略で were・had・should が文頭に出る（Were I you＝If I were you）", lv:1 },
  { id:"eig-066", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語句を選べ。", s:"If she had studied harder, she ( ) the exam.", o:["would pass","passes","had passed","would have passed"], a:3, e:"仮定法過去完了はif+had+過去分詞, 主語+would have+過去分詞の形をとる。", k:"・仮定法過去完了＝過去の事実に反する仮定「〜していたら…だったのに」。主節は would have＋過去分詞\n・混合型＝If＋had＋過去分詞（過去の条件）, 主語＋would＋原形（現在の結果）。主節の now／today が目印\n・If の省略で had が主語の前に出る（Had she studied harder, …）\n・見分け方＝主節は必ず助動詞＋have＋過去分詞。had＋過去分詞は if 節側の形", lv:3 },
  { id:"eig-067", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語を選べ。", s:"I wish I ( ) more free time.", o:["had","have","will have","having"], a:0, e:"現在の事実に反する願望はwish+主語+過去形で表す。", t:"wish+過去形は現在の願望、wish+had+過去分詞は過去の願望を表す。", k:"・I wish＋仮定法は実現困難な願望。現在の願望は過去形、過去の願望は had＋過去分詞\n・I wish＋主語＋would＋原形は「〜してくれればいいのに」（it would stop raining）\n・I hope＋直説法は実現可能な願望（I hope you pass）。wish との違いは実現性\n・If only＋仮定法は I wish より強い願望「〜でさえあれば」。時制のずれの規則は同じ", lv:1 },
  { id:"eig-068", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語句を選べ。", s:"I wish I ( ) the truth earlier.", o:["knew","had known","know","have known"], a:1, e:"過去の事実に反する願望はwish+主語+had+過去分詞で表す。", k:"・wish の時点より前の内容は had＋過去分詞。earlier／then／at that time が過去の目印\n・wish が過去形（wished）でも、続く節の形は wish の時点との前後関係で決まる\n・as if も同じ規則。as if he had seen it（見ていないのに見たかのように）\n・It is time＋主語＋過去形（It is time you went to bed）も仮定法の慣用表現", lv:3 },
  { id:"eig-069", cat:"英語", sub:"文法・仮定法", q:"空所に入る最も適切な語を選べ。", s:"He talks as if he ( ) everything.", o:["knows","known","knew","has known"], a:2, e:"as ifの後で現実と異なる内容を述べるときは過去形(仮定法過去)を使う。", t:"as ifの後は現実との違いを表すため、時制を一つ過去にずらすのが基本。", k:"・as if／as though の後は現実と異なる内容なら仮定法。同時なら過去形、それ以前なら had＋過去分詞\n・主節が過去形（He talked as if he knew）でも as if 節の過去形はそのまま\n・現実にあり得る内容なら直説法（It looks as if it will rain）も使う\n・仮定法を導く他の表現＝without／but for（〜がなければ）、otherwise（さもなければ）", lv:2 },

  { id:"eig-070", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語句を選べ。", s:"This bag is ( ) as that one.", o:["heavy","heavier","the heaviest","as heavy"], a:3, e:"原級比較はas+形容詞の原級+asの形で表す。", k:"・原級比較＝as＋原級＋as。否定は not as（so）… as「〜ほど…でない」。倍数は twice as … as\n・名詞を含む形＝as many books as（数）、as much money as（量）\n・慣用＝as … as possible（できるだけ）、not so much A as B（AというよりB）\n・that one の one は bag の代用。比較の対象は同じ形をそろえる", lv:2 },
  { id:"eig-071", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語句を選べ。", s:"The more you practice, ( ) you become.", o:["the better","better","the best","good"], a:0, e:"「〜すればするほど…」はthe+比較級, the+比較級の構文で表す。", k:"・the＋比較級＋主語＋動詞, the＋比較級＋主語＋動詞。名詞を伴うなら the more books you read と一緒に前へ出す\n・単独用法「〜すればそれだけ」＝The sooner, the better（早いほどよい）\n・比較級の強調は much／far／even／still／a lot。very は比較級には付かない\n・比較級＋and＋比較級（more and more）は「ますます〜」", lv:2 },
  { id:"eig-072", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語句を選べ。", s:"Mt. Fuji is ( ) mountain in Japan.", o:["higher","the highest","highest","the higher"], a:1, e:"最上級には通常theを付ける。the+最上級で「最も〜」を表す。", k:"・最上級の形＝the＋-est（短い語）／the most＋原級（長い語）。副詞の最上級は the 省略可\n・範囲は in＋場所・集団（in Japan）、of＋複数（of all／of the three）\n・one of the＋最上級＋複数名詞「最も〜なものの一つ」\n・higher than any other mountain（他のどの山より高い）は最上級と同義", lv:2 },
  { id:"eig-073", cat:"英語", sub:"文法・比較", q:"次の文とほぼ同じ意味になるものを選べ。", s:"Tom is not as tall as Ken.", o:["Tom is taller than Ken.","Tom and Ken are the same height.","Ken is taller than Tom.","Ken is not tall."], a:2, e:"「TomはKenほど背が高くない」は「Kenの方が背が高い」と同義。", t:"notを含む比較の文は、逆の立場から言い換えると意味を取りやすい。", k:"・A is not as … as B＝B is 比較級 than A。否定の原級比較は「Bの方が上」と読み替える\n・A is less … than B も「Bの方が上」。not as／less はともに劣位\n・同等＝as tall as／the same height。比較級 than を含めば必ず差がある\n・no taller than（同じくらい低い）と not taller than（より高くはない）は意味が異なる", lv:2 },
  { id:"eig-074", cat:"英語", sub:"文法・比較", q:"空所に入る最も適切な語を選べ。", s:"This question is ( ) difficult than the last one.", o:["fewer","least","the less","less"], a:3, e:"数えられない性質・程度の少なさはlessで表す。fewerは数えられる名詞に使う。", k:"・less＋不可算名詞、fewer＋可算名詞複数（ともに「より少ない」）。less＋形容詞は劣勢比較級\n・劣勢比較の最上級は the least（最も〜でない）。優勢比較は more difficult\n・little-less-least（量）、few-fewer-fewest（数）の変化\n・no more than（たった〜）と no less than（〜も）、not more than（多くとも）は対で覚える", lv:3 },

  { id:"eig-075", cat:"英語", sub:"不規則動詞", q:"goの過去分詞形として正しいものはどれか。", o:["gone","went","goed","going"], a:0, e:"go-went-goneと変化する。過去分詞はgone。", k:"・変化の型＝A-B-C（go-went-gone）、A-B-B（buy-bought-bought）、A-A-A（put-put-put）\n・have gone to（行ってしまって今いない）と have been to（行ったことがある）の区別は頻出\n・過去分詞の役割＝完了形（have＋過去分詞）、受動態（be＋過去分詞）、名詞修飾\n・-en で終わる過去分詞＝given／taken／written／spoken", lv:1 },
  { id:"eig-076", cat:"英語", sub:"不規則動詞", q:"breakの過去形として正しいものはどれか。", o:["breaked","broke","broken","break"], a:1, e:"break-broke-brokenと変化する。過去形はbroke。", t:"不規則動詞の変化は語呂合わせで覚えると忘れにくい。", k:"・同型＝speak-spoke-spoken、choose-chose-chosen、steal-stole-stolen\n・have の後は過去分詞（have broken）、単独の過去の出来事は過去形（broke）。混同がひっかけ\n・規則動詞化した誤形（breaked、goed、catched）は必ず誤り\n・受動態は be＋過去分詞（was broken）。broke は受動態に使えない", lv:1 },
  { id:"eig-077", cat:"英語", sub:"不規則動詞", q:"空所に入る最も適切な語を選べ。", s:"I have already ( ) the letter.", o:["wrote","writing","written","writes"], a:2, e:"write-wrote-writtenと変化する。現在完了には過去分詞writtenを使う。", k:"・同型＝drive-drove-driven、ride-rode-ridden、rise-rose-risen\n・already（すでに）は完了用法の目印。have と過去分詞の間に置く\n・rise（上がる・自動詞）と raise-raised（上げる・他動詞）は混同注意\n・lie-lay-lain（横たわる）と lay-laid-laid（置く）も同様。lie の過去形＝lay の原形", lv:2 },
  { id:"eig-078", cat:"英語", sub:"不規則動詞", q:"空所に入る最も適切な語を選べ。", s:"The concert ( ) at seven last night.", o:["begun","begins","beginned","began"], a:3, e:"begin-began-begunと変化する。過去形はbegan。", k:"・i-a-u 型＝drink-drank-drunk、sing-sang-sung、swim-swam-swum\n・last night／yesterday／〜ago は過去形の目印。過去の一点を示す語句\n・begun は過去分詞で単独では述語になれない（has begun が必要）。beginned は存在しない\n・run-ran-run、come-came-come は A-B-A 型", lv:1 },
  { id:"eig-079", cat:"英語", sub:"不規則動詞", q:"動詞の変化(原形-過去形-過去分詞)が誤っているものはどれか。", o:["catch-catched-caught","eat-ate-eaten","choose-chose-chosen","bring-brought-brought"], a:0, e:"catchの正しい変化はcatch-caught-caughtで、catchedという形は存在しない。", t:"catch-caught, teach-taughtのように-ght型の変化をまとめて覚えると良い。", k:"・-ght 型（A-B-B）＝teach-taught、buy-bought、think-thought、fight-fought\n・A-B-B 型の他の例＝make-made、find-found、tell-told、keep-kept\n・A-A-A 型（無変化）＝put、cut、set、read（過去形・過去分詞は /red/）\n・不規則動詞に -ed を付けた形（teached、buyed）は存在しない", lv:2 },

  { id:"eig-080", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: Could you pass me the salt? / B: ( )", o:["Nice to meet you.","Sure, here you are.","See you later.","I'm fine, thanks."], a:1, e:"依頼に応じるときはSure, here you are.のような表現が自然。", k:"・Could you／Would you＋原形は依頼。応じる＝Sure.／Certainly.／No problem.\n・Here you are.／Here it is.（はい、どうぞ）は物を手渡す定型\n・Would you mind＋-ing? への承諾は否定形（Not at all.）。Yes は断りになる\n・Shall I 〜?（〜しましょうか）は申し出。応答は Yes, please.", lv:1 },
  { id:"eig-081", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: How about going for a walk? / B: ( )", o:["You're welcome.","Excuse me.","That sounds great.","I'm sorry to hear that."], a:2, e:"提案に賛成するときはThat sounds great.などの表現を使う。", k:"・提案の表現＝How about＋-ing?、Why don't we 〜?、Let's 〜、Shall we 〜?\n・賛成＝Good idea.／Why not?、断り＝I'd love to, but 〜\n・Why not? は提案への賛成「いいね」、Why don't you 〜? は相手への勧め「〜したらどう？」\n・I'm sorry to hear that. は悪い知らせへの同情。場面の不一致が誤答の目印", lv:1 },
  { id:"eig-082", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: Excuse me, may I sit here? / B: ( )", o:["It's very kind of you.","Yes, please.","Not at all, thanks.","Sure, go ahead."], a:3, e:"許可を求める May I ~? には Sure, go ahead.（どうぞ）で応じる。", t:"許可を求める疑問文には、承諾か断りかをはっきり示す表現を選ぶ。", k:"・許可を求める表現＝May I／Can I＋原形。承諾＝Certainly.、断り＝I'm afraid not.\n・Do you mind if I 〜? への承諾は No, not at all.／Go ahead. Yes は断り\n・Is this seat taken?（この席は空いていますか）→ No, go ahead.（空いている）\n・It's very kind of you.（ご親切に）は親切への礼", lv:2 },
  { id:"eig-083", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: I'm sorry I'm late. / B: ( )", o:["That's all right.","You're welcome.","I hope so.","Congratulations."], a:0, e:"謝罪への返答としてはThat's all right.(大丈夫ですよ)が適切。", k:"・謝罪への応答＝That's OK.／No problem.／Never mind.\n・I'm sorry には謝罪のほか同情（I'm sorry to hear that.）の意味もあり、応答が変わる\n・お礼への応答＝You're welcome.／My pleasure.、祝福＝Congratulations.\n・I hope so.（そうだといいね）⇔ I hope not.（そうでないといいね）", lv:1 },
  { id:"eig-084", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: Would you like some more coffee? / B: ( )", o:["Yes, I am.","No, thank you. I'm fine.","I'm sorry, I can't.","No, I don't."], a:1, e:"勧められたものを断るときはNo, thank you. I'm fine.のように答える。", k:"・Would you like 〜?（〜はいかがですか）は物を勧める表現。承諾＝Yes, please.\n・Would you like to＋原形?（〜しませんか）は誘い。応答＝I'd love to.\n・勧める文の some は疑問文でも any にしない。相手の Yes を期待する疑問文\n・Yes, I am.／No, I don't. は be 動詞・do の疑問文への応答で形が合わない", lv:1 },
  { id:"eig-085", cat:"英語", sub:"会話表現", q:"Bの応答として最も自然なものを選べ。", s:"A: How long does it take to get to the station? / B: ( )", o:["I like the station.","It's on Monday.","About ten minutes by bus.","I go there every day."], a:2, e:"所要時間を尋ねる質問には具体的な時間で答える。", t:"How longの質問には具体的な時間や期間で答える。", k:"・It takes＋時間＋to 〜（〜するのに時間がかかる）が所要時間の基本形\n・How far（距離）→ two kilometers、How often（頻度）→ twice a week、How much（金額）\n・How long は「期間」の意味もあり、How long have you 〜? には for／since で答える\n・時間は take、費用は cost（It costs 500 yen）", lv:2 },

  { id:"eig-086", cat:"英語", sub:"長文読解", q:"本文の内容と一致するものはどれか。", s:"Many cities are building more bicycle lanes. This helps reduce traffic jams. It also lowers air pollution. Riding a bike is good exercise, too. In some countries, more people now bike to work than before. Local governments often give money to support these programs. Bicycle sharing systems have become popular in big cities. They let people rent bikes for short trips easily.", o:["自転車通勤をする人は年々減っている。","自転車シェアリングの人気は落ちている。","自治体は自転車政策に資金を出さない。","自転車道の整備は渋滞緩和に役立つ。"], a:3, e:"本文2文目に、自転車道の整備は交通渋滞を減らすのに役立つとある。", k:"・「本文と一致するもの」は設問と選択肢を先に読み、各選択肢の該当箇所を本文で照合する\n・誤答の型＝本文と逆の内容（減っている⇔増えている）、本文にない断定（資金を出さない）\n・言い換え＝reduce traffic jams（渋滞を減らす）→渋滞緩和、lower air pollution（大気汚染を減らす）\n・頻出語＝bicycle lane（自転車道）、local government（自治体）、rent（借りる）", lv:1 },
  { id:"eig-087", cat:"英語", sub:"長文読解", q:"本文によると、水分不足で起こりやすいものはどれか。", s:"Water is essential for all living things. The human body is about sixty percent water. We lose water every day through sweat and breathing. That is why we need to drink water regularly. Doctors often suggest drinking about two liters a day. However, the right amount can change with exercise and weather. Drinking too little water can cause headaches and tiredness. Drinking enough water keeps our brain and body working well.", o:["頭痛や疲労感","視力の向上","体重の増加","筋肉の強化"], a:0, e:"本文後半に、水分が少なすぎると頭痛や疲労感を引き起こすとある。", k:"・「〜で起こりやすいもの」は原因→結果の文を探す。cause（〜を引き起こす）、lead to（〜につながる）が目印\n・本文の言い換え＝headaches and tiredness（頭痛と疲労）→頭痛や疲労感。名詞の日本語訳が選択肢になる\n・頻出語＝essential（不可欠な）、regularly（定期的に）、amount（量）\n・however（しかし）は流れの転換の目印で、設問の根拠がその直後に来やすい", lv:1 },
  { id:"eig-088", cat:"英語", sub:"長文読解", q:"在宅勤務について本文が述べていないことはどれか。", s:"Many companies now let employees work from home. This can save time and money on commuting. Workers often feel more relaxed at home. However, some people miss talking with coworkers in person. Managers sometimes worry about checking on progress. Many companies now use online meetings instead. Some workers say they focus better without office noise. Others find it hard to separate work from daily life.", o:["通勤時間や交通費を減らせる。","全ての社員が満足している。","同僚と話す機会が減る。","オンライン会議で連絡を取る。"], a:1, e:"本文には満足していない人もいると書かれており、全員が満足しているとは述べていない。", t:"「述べられていないこと」を選ぶ問題は消去法で確実な記述を除いていく。", k:"・「述べていないもの」は本文にある3つを消去する。「全て」「常に」「決して」など極端な語を含む選択肢は要注意\n・some（一部の人）、others（他の人）、sometimes は「全員ではない」の根拠\n・言い換え＝save money on commuting（通勤費を節約）→交通費を減らせる\n・頻出語＝employee（従業員）、in person（直接会って）、focus（集中する）", lv:3 },
  { id:"eig-089", cat:"英語", sub:"長文読解", q:"本文によると、就寝前の読書がスマホより良い理由は何か。", s:"Reading books before bed can help people relax. It is often better than looking at a phone screen. Phone light can make it harder to fall asleep. Reading a paper book does not have this problem. Some studies show that reading lowers stress levels. A calm mind usually leads to better sleep. Even ten minutes of reading can make a difference. Try turning off your phone and picking up a book tonight.", o:["本が安いから","内容が面白いから","スマホの光で寝つきが悪くなるから","スマホが重すぎるから"], a:2, e:"本文に、スマホの光は寝つきを悪くするので紙の本の方が問題がないとある。", k:"・理由を問う設問は because／so／that is why などの因果表現を探す\n・make＋目的語＋形容詞（make it harder＝より難しくする）の型が理由を示す\n・頻出語＝fall asleep（眠りにつく）、calm（穏やかな）、make a difference（効果がある）\n・命令文 Try＋-ing（試しに〜してみる）は筆者の提案で、設問の根拠にはならない部分", lv:2 },
  { id:"eig-090", cat:"英語", sub:"長文読解", q:"本文の内容と一致するものはどれか。", s:"Farmers around the world face new problems from climate change. Rain patterns are becoming less predictable. Some areas now get too much rain, causing floods. Other areas get too little, causing droughts. These changes make it harder to plan when to plant crops. Scientists are developing new types of seeds that can survive harsh weather. Farmers are also learning new ways to save water. Working together, they hope to keep producing enough food.", o:["全地域で雨が増えている。","科学者は種子開発をやめた。","農家は節水を学んでいない。","雨量が予測しにくくなっている。"], a:3, e:"本文2文目に、雨のパターンが予測しにくくなっているとある。", k:"・誤答の型＝部分を全体にすり替え（Some areas→全地域）、動作の打ち消し（developing→やめた）\n・less predictable（予測しにくい）は劣勢比較級。predict（予測する）の派生語\n・頻出語＝climate change（気候変動）、flood（洪水）、drought（干ばつ）、crop（作物）\n・causing floods は分詞構文で結果「〜を引き起こして」を表す", lv:2 },

  { id:"eig-091", cat:"英語", sub:"発音・アクセント", q:"下線部の発音が他と異なるものはどれか。", o:["fo【o】d","c【oo】k","b【oo】k","l【oo】k"], a:0, e:"foodの【oo】は/uː/と発音するが、他は短い/ʊ/と発音する。", t:"母音字ooやeaは単語によって発音が変わるので個別に覚える。", k:"・oo の発音＝長い /uː/（food、school、moon、too）と短い /ʊ/（book、cook、look、good、foot）\n・oo の後に k が来ると短い /ʊ/ になることが多い（book、cook、look、took）\n・例外＝blood、flood は /ʌ/、door、floor は /ɔː/\n・同種の出題＝ea（sea／bread）、ou（house／country）、ow（now／know）", lv:2 },
  { id:"eig-092", cat:"英語", sub:"発音・アクセント", q:"下線部の発音が他と異なるものはどれか。", o:["br【ea】d","s【ea】","h【ea】d","w【ea】ther"], a:1, e:"seaの【ea】は/iː/と発音するが、他は/e/と発音する。", k:"・ea の発音＝/iː/（sea、tea、teach、easy）、/e/（bread、head、weather、heavy、ready）\n・/eɪ/ の例外＝great、break、steak。ear は /ɪə/（hear）と /ɜː/（early、learn）\n・read は現在形 /riːd/ と過去形・過去分詞 /red/ で発音が変わる\n・確実に読める語（bread、sea）を基準に他を分類する", lv:2 },
  { id:"eig-093", cat:"英語", sub:"発音・アクセント", q:"最も強く発音する部分の位置が他と異なるものはどれか。", o:["【pho】to","【mu】sic","de【sign】","【pa】per"], a:2, e:"designは第2音節にアクセントがあるが、他は第1音節にアクセントがある。", k:"・2音節語は名詞なら第1音節、動詞なら第2音節にアクセントを置く傾向。design は名詞も動詞も第2音節\n・名前動後＝同じ綴りで名詞は前、動詞は後。récord（記録）／recórd（記録する）\n・接頭辞 de-／re-／be-／a- で始まる語は第2音節が多い（report、begin、about）\n・-tion の語は直前の音節にアクセント（in-for-má-tion）", lv:3 },
  { id:"eig-094", cat:"英語", sub:"発音・アクセント", q:"下線部の発音が他と異なるものはどれか。", o:["【ch】air","【ch】eese","【ch】oose","【Ch】ristmas"], a:3, e:"Christmas の ch は /k/ と発音するが、他は /tʃ/ と発音する。", t:"ギリシャ語由来の語（chemistry, character, chorus）の ch は /k/ になりやすい。", k:"・ch の発音は3種＝/tʃ/（chair、church）、/k/（school、stomach）、/ʃ/（machine、chef）\n・/ʃ/ はフランス語由来の語（machine、chef）\n・同種の問題＝th（/θ/ think／/ð/ this）、g（/g/ get／/dʒ/ gentle）\n・語末の -ch は /tʃ/（much、rich）が多いが、stomach、ache は /k/", lv:3 },
  { id:"eig-095", cat:"英語", sub:"発音・アクセント", q:"最も強く発音する部分の位置が他と異なるものはどれか。", o:["ho【tel】","【ta】ble","【win】dow","【gar】den"], a:0, e:"hotelは第2音節にアクセントがあるが、他は第1音節にアクセントがある。", t:"アクセント問題は品詞で位置が変わる単語に注意する。", k:"・第1音節にアクセントを置く2音節名詞（table、window、garden、paper）に対し、hotel は第2音節\n・日本語と位置が異なる外来語＝hotél、guitár、políce、Japán、succéss、evént、machíne\n・-eer／-ese／-oo の語は語末にアクセント（enginéer、Japanése、bambóo）\n・カタカナ語は誤りやすい。cóffee（第1音節）、piáno（第2音節）", lv:1 }
];
