window.BANK_eigoA = [
 {id:"eig-001",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"increase",o:["produce","decrease","expand","continue"],a:1,e:"increase（増加する）の対義語は decrease（減少する）。expand は「拡大する」で類義側です。",t:"接頭辞 de- は「下へ・減る」方向を示すことが多い。",lv:1},
 {id:"eig-002",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"ancient",o:["modern","famous","natural","serious"],a:0,e:"ancient（古代の）⇔ modern（現代の）。",lv:1},
 {id:"eig-003",cat:"英語",sub:"語彙・意味",q:"次の語の意味として正しいものはどれか。",s:"reduce",o:["繰り返す","減らす","置き換える","調査する"],a:1,e:"reduce は「減らす、削減する」。名詞形は reduction です。",t:"3R（Reduce・Reuse・Recycle）から連想できます。",lv:1},
 {id:"eig-004",cat:"英語",sub:"語彙・意味",q:"次の語の意味として正しいものはどれか。",s:"necessary",o:["必要な","可能な","十分な","便利な"],a:0,e:"necessary は「必要な」。possible が「可能な」、convenient が「便利な」です。",lv:1},
 {id:"eig-005",cat:"英語",sub:"語彙・意味",q:"次の空欄に入る語として正しいものはどれか。",s:"If I ( ) rich, I would buy a house.",o:["am","was","were","will be"],a:2,e:"現在の事実に反する仮定を表す仮定法過去。主語が I でも be動詞は were を用いるのが原則です。",t:"帰結節に would があれば仮定法、と見抜くのが最短。",lv:2},
 {id:"eig-006",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"I have been living here ( ) 2010.",o:["for","since","from","during"],a:1,e:"現在完了で起点を示すときは since。for は期間の長さに使います。",t:"since＋時点、for＋期間。セットで覚える。",lv:2},
 {id:"eig-007",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"She is good ( ) playing tennis.",o:["at","in","for","with"],a:0,e:"be good at ~ で「〜が得意である」。",lv:1},
 {id:"eig-008",cat:"英語",sub:"語彙・意味",q:"次の空欄に入る語として正しいものはどれか。",s:"The man ( ) lives next door is a doctor.",o:["which","who","whom","what"],a:1,e:"先行詞が人で、関係詞節の主語にあたるため主格の who を用います。",t:"人＋主格＝who、人＋目的格＝whom（またはwho）。",lv:2},
 {id:"eig-009",cat:"英語",sub:"語彙・意味",q:"次の空欄に入る語として正しいものはどれか。",s:"The bridge ( ) built in 1990.",o:["is","was","has","were"],a:1,e:"1990年という過去の時点なので過去形の受動態 was built。主語が単数なので were は不可です。",lv:2},
 {id:"eig-010",cat:"英語",sub:"前置詞",q:"次の空欄に入る語句として正しいものはどれか。",s:"This bag is ( ) than that one.",o:["expensive","more expensive","most expensive","the most expensive"],a:1,e:"than があるので比較級。expensive のような長い語は more をつけます。",lv:1},
 {id:"eig-011",cat:"英語",sub:"熟語・句動詞",q:"次の動詞の過去形として正しいものはどれか。",s:"bring",o:["bringed","brang","brought","braught"],a:2,e:"bring − brought − brought と変化する不規則動詞です。",t:"buy−bought、think−thought と同じ型でまとめて覚える。",lv:2},
 {id:"eig-012",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"They decided to put off the meeting.",o:["中止する","延期する","開催する","短縮する"],a:1,e:"put off は「延期する」で postpone と同義。中止は call off です。",t:"put off と call off は対で出題されやすい。",lv:2},
 {id:"eig-013",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"I am looking forward to seeing you.",o:["会うのを楽しみにしている","会うのをためらっている","会う予定を立てている","会うのを忘れていた"],a:0,e:"look forward to ~ing で「〜を楽しみに待つ」。to のあとは動名詞になる点が頻出です。",lv:2},
 {id:"eig-014",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"Don't give up so easily.",o:["油断する","あきらめる","言い返す","引き受ける"],a:1,e:"give up は「あきらめる、放棄する」。",lv:1},

 {id:"eig-015",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"begin",o:["end","stop","start","continue"],a:2,e:"begin と start はどちらも「始める」という意味の同意語。end は反対の意味です。",lv:2},
 {id:"eig-016",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"huge",o:["enormous","tiny","average","narrow"],a:0,e:"huge と enormous はどちらも「巨大な」という意味。tiny は正反対の意味です。",t:"反意語に見える選択肢を混ぜたひっかけに注意。",lv:2},
 {id:"eig-017",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"glad",o:["sad","angry","tired","happy"],a:3,e:"glad と happy はどちらも「うれしい」という意味の同意語です。",lv:2},
 {id:"eig-018",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"correct",o:["wrong","right","false","fake"],a:1,e:"correct と right はどちらも「正しい」という意味。wrong は反対の意味です。",lv:2},
 {id:"eig-019",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"quick",o:["slow","calm","fast","quiet"],a:2,e:"quick と fast はどちらも「速い」という意味の同意語です。",lv:1},
 {id:"eig-020",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"reply",o:["question","ignore","ask","answer"],a:3,e:"reply と answer はどちらも「答える、返事をする」という意味です。",lv:2},
 {id:"eig-021",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"purchase",o:["buy","sell","borrow","lend"],a:0,e:"purchase と buy はどちらも「買う」という意味の同意語。sell は「売る」で反対です。",t:"purchase はビジネス文書などで使われるやや硬い語。",lv:2},
 {id:"eig-022",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"display",o:["hide","remove","show","cover"],a:2,e:"display と show はどちらも「見せる、示す」という意味です。",lv:2},
 {id:"eig-023",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"obtain",o:["lose","give","spend","get"],a:3,e:"obtain と get はどちらも「手に入れる」という意味の同意語。lose は反対の意味です。",lv:3},
 {id:"eig-024",cat:"英語",sub:"語彙・同意語",q:"次の語の同意語として正しいものはどれか。",s:"permit",o:["forbid","refuse","deny","allow"],a:3,e:"permit と allow はどちらも「許可する」という意味の同意語です。",t:"permit・allow・approve は「許可」グループとしてまとめて覚える。",lv:3},

 {id:"eig-025",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"difficult",o:["hard","easy","complex","serious"],a:1,e:"difficult（難しい）の対義語は easy（簡単な）。hard は difficult の類義語なので注意。",t:"hard は同意語で反意語ではない、ひっかけに注意。",lv:2},
 {id:"eig-026",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"wide",o:["broad","tall","long","narrow"],a:3,e:"wide（広い）の対義語は narrow（狭い）。broad は wide の類義語です。",lv:2},
 {id:"eig-027",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"strong",o:["weak","powerful","tough","solid"],a:0,e:"strong（強い）の対義語は weak（弱い）。powerful は strong の類義語です。",lv:1},
 {id:"eig-028",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"arrive",o:["enter","remain","depart","stay"],a:2,e:"arrive（到着する）の対義語は depart（出発する）。",lv:2},
 {id:"eig-029",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"accept",o:["agree","receive","allow","refuse"],a:3,e:"accept（受け入れる）の対義語は refuse（拒否する）。",lv:2},
 {id:"eig-030",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"borrow",o:["keep","return","take","lend"],a:3,e:"borrow（借りる）の対義語は lend（貸す）。return（返す）と混同しないよう注意。",t:"borrow＝借りる／lend＝貸す。動作の主体で区別する。",lv:3},
 {id:"eig-031",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"success",o:["failure","victory","effort","result"],a:0,e:"success（成功）の対義語は failure（失敗）。victory は success に近い意味の語です。",lv:3},
 {id:"eig-032",cat:"英語",sub:"語彙・反意語",q:"次の語の対義語として正しいものはどれか。",s:"cheap",o:["low","small","expensive","free"],a:2,e:"cheap（安い）の対義語は expensive（高い）。",lv:2},

 {id:"eig-033",cat:"英語",sub:"語彙・意味",q:"次の語の意味として正しいものはどれか。",s:"cancel",o:["中止する","開催する","延期する","継続する"],a:0,e:"cancel は「中止する、取り消す」という意味の動詞です。",t:"cancel（中止）と postpone（延期）を混同しないよう注意。",lv:1},
 {id:"eig-034",cat:"英語",sub:"語彙・意味",q:"次の語の意味として正しいものはどれか。",s:"improve",o:["悪化する","維持する","改善する","無視する"],a:2,e:"improve は「改善する、良くなる」という意味の動詞です。",lv:2},
 {id:"eig-035",cat:"英語",sub:"語彙・意味",q:"次の語の意味として正しいものはどれか。",s:"repair",o:["破壊する","購入する","交換する","修理する"],a:3,e:"repair は「修理する」という意味の動詞。fix も同義で使われます。",lv:2},
 {id:"eig-036",cat:"英語",sub:"語彙・意味",q:"次の語の意味として正しいものはどれか。",s:"polite",o:["失礼な","礼儀正しい","親しい","厳しい"],a:1,e:"polite は「礼儀正しい」という意味の形容詞です。",lv:2},
 {id:"eig-037",cat:"英語",sub:"語彙・意味",q:"次の語の意味として正しいものはどれか。",s:"avoid",o:["避ける","求める","受け入れる","直面する"],a:0,e:"avoid は「避ける」という意味。face（直面する）とは逆の意味合いです。",t:"avoid のあとは動名詞（~ing）が続く。",lv:3},

 {id:"eig-038",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"Please turn off the light before you leave.",o:["消す","つける","直す","壊す"],a:0,e:"turn off は「（電気などを）消す」という意味。反対は turn on（つける）です。",lv:1},
 {id:"eig-039",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"I ran into an old friend at the station.",o:["無視する","追いかける","偶然出会う","避ける"],a:2,e:"run into ~ は「〜に偶然出会う」という意味。run away（逃げる）と混同しないように。",t:"run into と come across は同じ意味でよく言い換えられる。",lv:2},
 {id:"eig-040",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"She takes after her mother.",o:["世話をする","似ている","反抗する","尊敬する"],a:1,e:"take after ~ は「（主に家族に）〜に似ている」という意味です。",lv:3},
 {id:"eig-041",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"He was brought up in a small town.",o:["雇われた","教育した","生まれた","育てられた"],a:3,e:"be brought up は「育てられる」。bring up は「育てる」という意味の熟語です。",t:"bring up には「話題を持ち出す」という意味もある。",lv:3},
 {id:"eig-042",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"They came across a beautiful lake during the hike.",o:["偶然見つける","横切る","登る","避けて通る"],a:0,e:"come across ~ は「〜を偶然見つける」という意味です。",lv:2},
 {id:"eig-043",cat:"英語",sub:"熟語・句動詞",q:"下線部の熟語の意味として正しいものはどれか。",s:"Please fill out this form.",o:["提出する","破棄する","記入する","確認する"],a:2,e:"fill out ~ は「（書類に）記入する」という意味。fill in も同義で使われます。",t:"fill out と fill in はどちらも「記入する」で言い換え可能。",lv:1},

 {id:"eig-044",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"He is interested ( ) history.",o:["on","in","at","to"],a:1,e:"be interested in ~ で「〜に興味がある」という意味です。",lv:1},
 {id:"eig-045",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"This train is bound ( ) Osaka.",o:["to","at","in","for"],a:3,e:"be bound for ~ で「〜行きである」という意味。駅や空港の案内でよく使われます。",t:"bound for ~ は乗り物の行き先を表す決まり文句。",lv:3},
 {id:"eig-046",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"She was absent ( ) school yesterday.",o:["from","in","at","by"],a:0,e:"be absent from ~ で「〜を欠席する」という意味です。",t:"absent は from とセットで覚える。",lv:3},
 {id:"eig-047",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"This bag is different ( ) mine.",o:["with","to","from","by"],a:2,e:"be different from ~ で「〜と異なる」という意味です。",lv:3},
 {id:"eig-048",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"We arrived ( ) the airport at noon.",o:["to","in","on","at"],a:3,e:"空港のような特定の地点への到着は arrive at。国や都市など広い範囲には arrive in を使います。",t:"arrive at＝地点、arrive in＝国・都市、と使い分ける。",lv:2},
 {id:"eig-049",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"I'm afraid ( ) dogs.",o:["from","of","at","with"],a:1,e:"be afraid of ~ で「〜を恐れる」という意味です。",lv:1},
 {id:"eig-050",cat:"英語",sub:"前置詞",q:"次の空欄に入る語として正しいものはどれか。",s:"Please wait ( ) me at the station.",o:["to","at","for","on"],a:2,e:"wait for ~ で「〜を待つ」という意味です。",lv:1}
];
